### ISSUE TITLE
TypeError: Cannot read property 'close' of null

### ISSUE THREAD

**Issue by ebuildy** [TBear79/rabbit-chatter#1]
Hello,

Sometimes I got the following error:

/node_modules/rabbit-chatter/lib/rabbit-chatter.js:68
                t._connectionTimer = setTimeout(() => { t._connection.close(); t._connection = null; }, 500);
                                                                     ^

TypeError: Cannot read property 'close' of null
    at Timeout._onTimeout (/node_modules/rabbit-chatter/lib/rabbit-chatter.js:68:58)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)

This makes my application crashed because the error logger ;-( quite funny ^^

Thanks you,

**Comment by TBear79** [comment]
Hi Thomas

As mentioned, I'll investigate this further.

Regards Thorbjørn

**Comment by ebuildy** [comment]
Cool, thanks you, no more bugs found, great!
