### ISSUE TITLE
Error: Frame size exceeds frame max

### ISSUE THREAD

**Issue by MichaelNeas** [TBear79/rabbit-chatter#11]
Hey,

Love your plugin for winston, recently I have been getting the error "ERROR in rabbit-chatter: Error: Frame size exceeds frame max" and I am sending messages to a rabbitmq instance that supports amqp .9-1, which is used by amqplib.  I am not sending messages anywhere near the max size on the rabbit instance.

I was wondering if any of you have come across this issue before?

**Comment by JimiC** [comment]
1. A frame consists of 3 parts, frame header, extended header and frame body (http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-transport-v1.0-os.html#section-framing).
You better investigate what is going on with the headers if you are sure that the body size is not exceeding the limit.
2. Make sure you use RabbitMQ v3.5.2+ (it contains a fix for the `x-death` header issue).

**Comment by MichaelNeas** [comment]
Thank you JimiC,

1. I have been stepping through a lot of this, and I have gotten to the error being thrown in framejs in ampqlib.  My max frame is 4096, with a requesting frame very much larger than that.  But when I toString the buffer I see a 400 error is getting returned to me from some where.

2. RabbitMQ 3.6.6 so good there

**Comment by MichaelNeas** [comment]
Resolution: The rabbitMQ instance was served over AWS which only allowed ports 80 and 443.  By removing the inspection of http headers amqp was able to reach successfully.
