### ISSUE TITLE
[Question] SyntaxError: Arrow function

### ISSUE THREAD

**Issue by JimiC** [TBear79/rabbit-chatter#4]
I have an issue and don't know how to resolve it.

I'm using the `winston-fast-rabbitmq` package as a logger transport to log to `RabbitMQ`.
That package has a dependency to this one as well to `dont-collide`.

[line 55](https://github.com/TBear79/rabbit-chatter/blob/master/lib/rabbit-chatter.js#L55) is causing the execution of my implementation to fail with the message mentioned in the title.

I'm writing in `Typescript` and the compiler is targeting `es5`.

How can I resolve this?

Thanks in advance.

**Comment by JimiC** [comment]
As commented also  in `dont-collide` using `(() => {})` instaead of `() => {}` is valid.

**Comment by Franco-Poveda** [comment]
Target es6. Arrow functions are a feature introduced on ECMAScript 2015.
Use nodejs >= 6.4
check nodejs es6 features support here: http://node.green/

**Comment by JimiC** [comment]
@Franco-Poveda Thanks for your info. I already knew that. The thing here is that we use `node 4.x` on our servers, so I'm forced to target `es5`. I'm using `vscode` and `Typescript` and the compiler is complaining about the arrow function in that particular place. As I said changing it to `(() => {})` does the trick as well as using `(() => void(0))`.

**Comment by TBear79** [comment]
@JimiC Hi. I've added the () around () => {}. It makes sense. Please update from npm.

**Comment by JimiC** [comment]
@TBear79 Thanks for understanding.
