### ISSUE TITLE
Sending sporadic messages leaves open connections

### ISSUE THREAD

**Issue by JimiC** [TBear79/rabbit-chatter#8]
While deploying an app that uses `Winston-Fast-RabbitMQ` for its logger, on our staging app server, I came across the issue of multiple connections being left open. When left unhandled all connection to the server are consumed thus leaving no other choice but to reboot the server.

I instantly knew that this was an issue with our `logger` and specifically with `rabbit-chatter`.

Upon investigating I discovered that `rabbit-chatter` had two fundamental flow errors.
1. The connection is set to timeout after a message was sent and in case no message was sent the connection is left open.
2. The function that determines whether to create a new connection or return the existing connection
**a.** doesn't take into account whether a connection is in the process of closing (so while returning that connection until it's time to sent the message or receive the response, the connection has closed)
**b.** doesn't handle correctly the `keep alive` process of the connection (timer isn't reset correctly)
**c.** creates multiple new connections on rapid message sending (it's an async function so there are time racing cases) but only stores the last one thus leaving the others open

**Comment by beazergood** [comment]
Hi @JimiC do you know when this'll be fixed? Was hoping to use this in conjunction with https://www.npmjs.com/package/winston-fast-rabbitmq but in it's current state it's unusable as my RabbitMQ server bombs out after a while due to too many connections being made.

Thanks!
Dave

**Comment by JimiC** [comment]
I'm currently testing the new code against our staging server. Things look promising but I want to stress test it a little longer. If I have to guess I would say probably by the end of next week.

**Comment by beazergood** [comment]
Ok cool, thanks for letting me know.  👍
